# Generated by Django 3.0.2 on 2020-02-11 03:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagueName', models.CharField(max_length=60)),
                ('leagueDescription', models.CharField(max_length=500)),
                ('joinKey', models.CharField(max_length=20)),
                ('leagueImage', models.ImageField(max_length=144, upload_to='uploads/%Y/%m/%d')),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerList', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tournaments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('leaderboard', django.contrib.postgres.fields.jsonb.JSONField()),
                ('wgr', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UnavailablePlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=20)),
                ('teamImage', models.ImageField(max_length=144, upload_to='uploads/%Y/%m/%d')),
                ('player1', models.IntegerField()),
                ('player2', models.IntegerField()),
                ('player3', models.IntegerField()),
                ('player4', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.League')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
