# Generated by Django 3.0.3 on 2020-02-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='player2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='player3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='player4',
            field=models.IntegerField(null=True),
        ),
    ]
