# Generated by Django 3.0.3 on 2020-03-30 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200219_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tID', models.IntegerField()),
                ('round1', models.IntegerField(null=True)),
                ('round2', models.IntegerField(null=True)),
                ('round3', models.IntegerField(null=True)),
                ('round4', models.IntegerField(null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='CurTourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tID', models.IntegerField()),
                ('endDate', models.DateField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.League')),
            ],
        ),
    ]
