# Generated by Django 3.0.3 on 2020-04-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200331_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='coursePar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='curRound',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='roundFin',
            field=models.IntegerField(default=0),
        ),
    ]
